apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "climbing_gym_model-backend.fullname" . }}-minio-data
  labels:
    app.kubernetes.io/name: {{ include "climbing_gym_model-backend.name" . }}-minio
    helm.sh/chart: {{ include "climbing_gym_model-backend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.minio.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.minio.storage.size }}
