default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: climbing_gym_model_dev
  username: climbing_gym_model
  password: password
  host: localhost

test:
  <<: *default
  database: climbing_gym_model_test
  username: climbing_gym_model
  password: password
  host: localhost

production:
  <<: *default
  database: climbing_gym_model_production
  username: climbing_gym_model
  password: <%= ENV["NALKA_DATABASE_PASSWORD"] %>
